# Generated by Django 6.0.3 on 2026-03-04 12:11

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=gallery.models.thumb_upload_to),
        ),
    ]
