# Generated by Django 6.0.3 on 2026-03-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_mediafile_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbs/'),
        ),
    ]
