# Generated by Django 6.0.3 on 2026-03-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_infotext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='media_type',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('demo_sound', 'Demo_Sound'), ('sound_source,', 'Sound_Source')], max_length=20),
        ),
    ]
